title: "Rajdeep Chakraborty"
author: "@raj-ch017"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "rajdeep_chakraborty_cv.pdf", title: "CV"}
  - {title: "Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rajdeep.ch138@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/raj-ch017"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/rajdeep-chakraborty-04a957218/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
